version: "3.7"
services:
  app:
    build:
      args:
        user: shoaib
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php
    depends_on:
      - "db"
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - aldi

  db:
    image: mysql:5.7
    container_name: db
    depends_on:
      - "nginx"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "aldi"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_PASSWORD: "password"
      MYSQL_USER: "aldi"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - aldi

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - aldi

networks:
  aldi:
    driver: bridge
